updated the release workflow

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -22,20 +22,30 @@ jobs:
         run: |
           echo "Releasing Apicurio Data Models version ${{ github.event.inputs.release-version }} from branch ${{ github.event.inputs.branch }}"
           echo "Next Snapshot version will be ${{ github.event.inputs.snapshot-version }}"
+
+
       - name: Set up Node.js v12
         uses: actions/setup-node@v1
         with:
           node-version: 12
+
+
       - name: Set up JDK 1.8
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
+
+
       - name: Set up settings.xml
         run: |
           echo "<settings><servers><server><id>${{ secrets.OSSRH_ID }}</id><username>${{ secrets.OSSRH_USERNAME }}</username><password>${{ secrets.OSSRH_TOKEN }}</password></server></servers><profiles><profile><id>${{ secrets.OSSRH_ID }}</id><activation><activeByDefault>true</activeByDefault></activation><properties><gpg.executable>gpg</gpg.executable><gpg.passphrase>${{ secrets.GPG_PASSPHRASE}}</gpg.passphrase></properties></profile></profiles></settings>" > /home/runner/.m2/settings.xml
           cat /home/runner/.m2/settings.xml
+
+
       - name: Set up Gren
         run: npm install github-release-notes -g
+
+
       - name: Cache Dependencies
         uses: actions/cache@v1
         with:
@@ -43,6 +53,8 @@ jobs:
           key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
           restore-keys: |
             ${{ runner.os }}-maven-
+
+
       - name: Apicurio Data Models Code Checkout
         run: |
           git init
@@ -55,6 +67,8 @@ jobs:
           git pull
           echo "#### Listing files after clone ####"
           find .
+
+
       - name: Apicurio Website Code Checkout
         run: |
           mkdir website
@@ -67,25 +81,44 @@ jobs:
           git checkout master
           git branch --set-upstream-to=origin/master
           git pull
+
+
       - name: Update Release Version ${{ github.event.inputs.release-version}}
         run: mvn versions:set -DnewVersion=${{ github.event.inputs.release-version}} -DgenerateBackupPoms=false -DprocessAllModules=true
+
+
       - name: Verify Build
         run: mvn clean install -Ptranspilation
+
+
       - name: Commit Release Version Change
         run: |
           git add .
           git commit -m "Automated version update: ${{ github.event.inputs.release-version}}"
           git push
+
+
       - name: Remove prefix '.Final' from package.json
         run: |
           pushd .
           cd target/ts
           sed -i "s/.Final//g" ./dist/package.json
           popd
+
+
       - name: Create '.npmrc' File 
         uses: filipstefansson/set-npm-token-action@v1
         with:
           token: ${{ secrets.NPM_TOKEN }}
+
+
+      - name: Import GPG Key
+        uses: crazy-max/ghaction-import-gpg@v1
+        env:
+          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
+          PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }} 
+
+
       - name: Create GitHub Release
         uses: actions/create-release@latest
         env:
@@ -93,27 +126,39 @@ jobs:
         with:
           tag_name: ${{ github.event.inputs.release-version}}       
           release_name: ${{ github.event.inputs.release-version}}
+
+
       - name: Generate Release Notes
         run: gren release --token=${{ secrets.GITHUB_TOKEN }} --override --prefix=v             
-      - name: Publish to Maven Central
-        uses: samuelmeuli/action-maven-publish@v1
-        with:
-          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
-          gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
-          nexus_username: ${{ secrets.OSSRH_USERNAME }}
-          nexus_password: ${{ secrets.OSSRH_TOKEN }}
-          maven_goals_phases: deploy --batch-mode --settings /home/runner/.m2/settings.xml -DskipTests
-          maven_profiles: release   
+
+
+      - name: Maven Deploy
+        run: |
+          # Retry 3 times before the steps actually fails
+          (echo "===== Maven Deploy Attempt: 1 ====" && mvn deploy -Prelease --batch-mode --settings /home/runner/.m2/settings.xml -DskipTests) || \
+          (echo "===== Maven Deploy Attempt 1 Failed - Sleeping for 30 minutes ====" && sleep 30m) || \
+          (echo "===== Maven Deploy Attempt: 2 ====" && mvn deploy -Prelease --batch-mode --settings /home/runner/.m2/settings.xml -DskipTests) || \
+          (echo "===== Maven Deploy Attempt 1 Failed - Sleeping for 4 hours ====" && sleep 4h) || \
+          (echo "===== Maven Deploy Attempt: 3 ====" && mvn deploy -Prelease --batch-mode --settings /home/runner/.m2/settings.xml -DskipTests) || \
+          (echo "==== Maven Deploy Step Failed ====" && exit 1)
+
+
       - name: Publish to NPM
         run: npm publish ./target/ts/dist/
+
+
       - name: Update Snapshot version ${{ github.event.inputs.snapshot-version}}
         run: mvn versions:set -DnewVersion=${{ github.event.inputs.snapshot-version}} -DgenerateBackupPoms=false -DprocessAllModules=true
+
+
       - name: Commit Snapshot Version Change
         run: |
           git add .
           git restore --staged .npmrc    # can't commit, contains NPM token
           git commit -m"Automated version update: ${{ github.event.inputs.snapshot-version}}"
           git push
+
+
       - name: Updating Project Website for Release ${{ github.event.inputs.release-version}}
         run: |
           cd website
@@ -127,7 +172,9 @@ jobs:
           cp latestRelease.json releases/$PUBLISHED_AT.json
           
           # setting up env variable to use in next step to force commit the file
-          echo "::set-env name=FILENAME::$PUBLISHED_AT" 
+          echo "::set-env name=FILENAME::$PUBLISHED_AT"
+
+
       - name: Commit Project Website Changes
         run: |
           cd website
